[package]
name = "stir"
version = "0.0.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]
rustversion = "1.0.4"

[dev-dependencies]
anyhow = "1.0.40"
executable-path = "1.0.0"
pretty_assertions = "0.7.2"
tempfile = "3.2.0"

[[bin]]
name = "stir_test_helper"
path = "src/test_helper.rs"
required-features = ["test_executables"]

[target.'cfg(not(target_os = "windows"))'.dependencies.gag]
version = "0.1.10"
optional = true

[target.'cfg(not(target_os = "windows"))'.dependencies.executable-path]
version = "1.0.0"
optional = true

[[bin]]
name = "context_integration_tests"
path = "src/context_integration_tests.rs"
required-features = ["test_executables"]

[features]
test_executables = ["gag", "executable-path"]
