[package]
name = "cradle"
version = "0.0.12"
description = "Execute child processes with ease"

authors = ["Sönke Hahn <soenkehahn@gmail.com>"]
license = "CC0-1.0"
edition = "2018"
repository = "https://github.com/soenkehahn/cradle"
homepage = "https://github.com/soenkehahn/cradle"

[dependencies]
rustversion = "1.0.4"

[dev-dependencies]
executable-path = "1.0.0"
pretty_assertions = "0.7.2"
tempfile = "3.2.0"

[[bin]]
name = "cradle_test_helper"
path = "src/test_helper.rs"
required-features = ["test_executables"]

[target.'cfg(unix)'.dependencies.gag]
version = "0.1.10"
optional = true

[target.'cfg(unix)'.dependencies.executable-path]
version = "1.0.0"
optional = true

[target.'cfg(unix)'.dependencies.nix]
version = "0.21.0"
optional = true

[[bin]]
name = "context_integration_tests"
path = "src/context_integration_tests.rs"
required-features = ["test_executables"]

[features]
test_executables = ["gag", "executable-path", "nix"]
