[package]
name = "stir"
version = "0.0.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
executable-path = "1.0.0"
tempfile = "3.2.0"

[[bin]]
name = "stir_test_helper"
path = "src/test_helper.rs"
required-features = ["build_test_helper"]

[features]
build_test_helper = []
