[package]
name = "stir"
version = "0.0.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies.gag]
version = "0.1.10"
optional = true

[dependencies.executable-path]
version = "1.0.0"
optional = true

[dev-dependencies]
executable-path = "1.0.0"
tempfile = "3.2.0"

[[bin]]
name = "stir_test_helper"
path = "src/test_helper.rs"
required-features = ["test_executables"]

[[bin]]
name = "context_integration_tests"
path = "src/context_integration_tests.rs"
required-features = ["test_executables"]

[features]
test_executables = ["gag", "executable-path"]
