[package]
name = "context-integration-tests"
version = "0.0.0"
edition = "2018"
publish = false

[target.'cfg(unix)'.dependencies]
cradle = { path = ".." }
executable-path = "1.0.0"
gag = "0.1.10"
tempfile = "3.2.0"
unindent = "0.1.7"
