name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  CACHE_KEY: 0

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        rust:
          - stable
          - "1.50"
          - "1.45"
          - "1.40"
          - "1.35"
          - "1.31"

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "--deny warnings"

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt

      # An issue with BSD Tar causes sporadic failures on macOS.
      # c.f https://github.com/actions/cache/issues/403
      - name: Install GNU Tar
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-tar
          echo /usr/local/opt/gnu-tar/libexec/gnubin > $GITHUB_PATH

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: cargo-${{ env.CACHE_KEY }}-${{ runner.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install just
        if: matrix.os == 'windows-latest'
        run: |
          if ! which just; then
            git clone https://github.com/casey/just
            cd just
            cargo install
          fi

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version
          cargo fmt --version

      - name: Ci
        run: |
          pwd
          bark
          just ci
