name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  CACHE_KEY: 0

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "--deny warnings"

    steps:
      - uses: actions/checkout@v2

      # An issue with BSD Tar causes sporadic failures on macOS.
      # c.f https://github.com/actions/cache/issues/403
      - name: Install GNU Tar
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-tar
          echo /usr/local/opt/gnu-tar/libexec/gnubin > $GITHUB_PATH

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: cargo-${{ env.CACHE_KEY }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install just
        run: |
          if ! which just; then
            cargo install just
          fi

      - name: Install Rust Toolchain Components
        run: |
          rustup component add clippy rustfmt

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version
          cargo fmt --version

      - name: Ci
        run: just ci
