name: Ci

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        rust:
          - stable
          - "1.41"
          - "1.42"
          - "1.43"
          - "1.44"
          - "1.45"
          - "1.46"
          - "1.47"
          - "1.48"
          - "1.49"
          - "1.50"
          - "1.51"
          - "1.52"
          - "1.53"
          - "1.54"

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "--deny warnings"

    steps:
      - uses: actions/checkout@v2

      - name: Install just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clippy and rustfmt
        run: |
          echo '${{ matrix.rust }}' > rust-toolchain
          rustup component add clippy rustfmt

      - name: Info
        run: |
          just --version
          rustup --version
          cargo --version
          cargo clippy --version
          cargo fmt --version

      - name: Ci
        run: just ci
